//tealium universal tag - utag.352 ut4.0.202604271126, Copyright 2026 Tealium.com Inc. All Rights Reserved.
function clear_reports_SiteTag_136(){var cr_cid=0;var tp_cid='';var params=window.location.search.substring(1).split('&');for(var i=0;i<params.length;i++){var pair=params[i].split('=');if((pair[0]=='cr_cid')&&pair[1]){cr_cid=parseInt(pair[1]);}
else if((pair[0]=='gclid')&&pair[1]){tp_cid=pair[1];}}
if(cr_cid||tp_cid){var d=new Date();d.setTime(d.getTime()+(365*24*60*60*1000));var expires='expires='+d.toUTCString()+'; ';var hostnameParts=window.location.hostname.split('.').reverse();var domain=hostnameParts[0];for(var j=1;j<hostnameParts.length;j++){domain=hostnameParts[j]+'.'+domain;document.cookie='cr___cd=1; '+expires+'domain='+domain+'; path=/';if(document.cookie.indexOf('cr___cd=1')>-1)
break;}
var cookieEnd='; '+expires+'domain='+domain+'; path=/';document.cookie='cr___cd='+domain+cookieEnd;if(cr_cid){document.cookie='cr___cid='+cr_cid+cookieEnd;}
if(tp_cid){document.cookie='cr___tpcid='+tp_cid+cookieEnd;}}}
function clear_reports_ConversionTag_136_Economist_CPL(){var wgti=new Date().getTime()+'.'+Math.random().toString(36).substring(5);var wgtv="";var cr_cid=0;var tp_cid='';var params=window.location.search.substring(1).split('&');for(var i=0;i<params.length;i++){var pair=params[i].split('=');if((pair[0]=='cr_cid')&&pair[1]){cr_cid=parseInt(pair[1]);}
else if((pair[0]=='gclid')&&pair[1]){tp_cid=pair[1];}}
var ca=document.cookie.split(';');for(var j=0;j<ca.length;j++){var c=ca[j].trim().split('=');if(!cr_cid&&(c[0]=='cr___cid')){cr_cid=c[1];}
else if(!tp_cid&&(c[0]=='cr___tpcid')){tp_cid=c[1];}}
var tag=document.createElement('script');tag.type='text/javascript';tag.src='https://www.clear-reports.com/track/conversion.php?ai=136&agpc=0756ghgjwbmFG5465405&wgn=Economist_CPL_Conversion&pci='+parseInt(cr_cid)+'&tpci='+encodeURIComponent(tp_cid)+'&ht=1&cachebuster='+Date.now()+'&wgtv='+wgtv+'&wgti='+wgti;document.body.appendChild(tag);}
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
try{clear_reports_SiteTag_136();}catch(e){}
}};utag.o[loader].loader.LOAD(id);})("352","teg.core");}catch(error){utag.DB(error);}
